[package]
name = "signal-crypto"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"

[dependencies]
aes = "0.6"
block-modes = "0.7"
ctr = "0.6"
hex = "0.4"
hmac = "0.9.0"
rand = "0.7.3"
sha-1 = "0.9"
sha2 = "0.9"
subtle = "2.2.3"
