[package]
name = "libsignal-jni"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"

[lib]
name = "signal_jni"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-protocol-rust = { git = "ssh://git@github.com/signalapp/libsignal-protocol-rust.git" }
jni = "0.17"
rand = "0.7.3"
