[package]
name = "device-transfer"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
boring = "2.0.0"
libc = "0.2"

[dev-dependencies]
hex = "0.4"
