[package]
name = "libsignal-net"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[dependencies]
async-trait = "0.1.41"
base64 = "0.21"
boring = { git = "https://github.com/signalapp/boring", branch = "libsignal" }
boring-sys = { git = "https://github.com/signalapp/boring", branch = "libsignal", default-features = false }
bytes = "1.4.0"
displaydoc = "0.2"
futures-util = "0.3.7"
http = "0.2.9"
http-body-util = "0.1.0-rc.3"
hyper = { version = "1.0.0-rc.4", features = ["http1", "http2", "client"] }
lazy_static = "1.4.0"
pin-project-lite = "0.2.4"
rustls-native-certs = "0.6.3"
thiserror = "1.0.38"
tokio = { version = "1", features = ["rt"] }
tokio-boring = { git = "https://github.com/signalapp/boring", branch = "libsignal" }
tokio-tungstenite = { version = "0.19.0" }
tungstenite = { version = "0.19.0" }
