name: CI

on: [pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Install nightly rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Check out libsignal-ffi
        uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://github.com".insteadOf ssh://git@github.com

      - name: Build libsignal-ffi
        run: make

# TODO: In the future, we should also run tests for our clients,
# to make sure a change doesn't break them (at least not unexpectedly).

  lint:
    # Lint in a separate job, using stable Rust.
    name: Formatting and linting

    runs-on: ubuntu-latest

    steps:
      - name: Check out libsignal-ffi
        uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://github.com".insteadOf ssh://git@github.com

      - name: Rustfmt check
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy
