name: Node

on:
  push:
    branches: [ master ]
    paths-ignore: ['swift/**', '*.podspec', 'java/**']
  pull_request:
    branches: [ master ]
    paths-ignore: ['swift/**', '*.podspec', 'java/**']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: minimal
    - run: nvm install && nvm use
      shell: bash -l {0}
    - run: yarn install
    - run: yarn lint
    - run: yarn format -c
    - run: yarn build
    - name: Run yarn test
      uses: GabrielBB/xvfb-action@v1.4
      with:
        # The tests use an Electron-based runner, so we need to set up a dummy display for them.
        run: yarn test
