name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore: ['swift/**']
  pull_request:
    branches: [ master ]
    paths-ignore: ['swift/**']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt, clippy
    - name: Check for duplicate dependencies
      run: |
        DUPS=$(cargo tree -d -e normal)
        echo $DUPS
        test -z "$DUPS"
    - name: Rustfmt check
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy
